type Reason = { [key in string]: string[] };

const types = [
  "VOLUNTARY",
  "WITH_JUST_CAUSE",
  "WITHOUT_JUST_CAUSE",
  "MUTUAL_AGREEMENT",
  "FIXED_TERM_CONTRACT",
  "TRIAL_PERIOD",
  "STAFF_ADJUSTMENT",
  "CANCELLATION_OF_CONTRACT",
];

const reasons: Reason = {
  VOLUNTARY: [
    "DIFFICULTIES_RELATED_TO_THE_WORK_ENVIRONMENT",
    "BETTER_SALARY_OPPORTUNITIES_AT_ANOTHER_COMPANY",
    "LACK_OF_PROFESSIONAL_DEVELOPMENT_OPPORTUNITIES",
    "LOCATION_CONDITIONS",
    "UNSATISFACTORY_WORKING_CONDITIONS",
    "PERSONAL_REASONS",
    "LEADERSHIP",
  ],
  WITH_JUST_CAUSE: [
    "DERELICTION_OF_DUTY",
    "UNJUSTIFIED_ABSENCES",
    "DISCIPLINARY_OFFENSES",
    "PERFORMANCE",
  ],
  WITHOUT_JUST_CAUSE: [
    "COMPANY_DECISION",
    "COMPLETION_OF_TEMPORARY_STAFF_WORK",
  ],
  MUTUAL_AGREEMENT: ["NEGOTIATION_BETWEEN_COMPANY_AND_EMPLOYEE"],
  FIXED_TERM_CONTRACT: ["END_OF_CONTRACTED_PERIOD"],
  TRIAL_PERIOD: ["DOES_NOT_PASS_THE_TRIAL_PERIOD"],
  STAFF_ADJUSTMENT: ["KITCHEN_OR_CP_CLOSURE", "PLANT_REDUCTION"],
  CANCELLATION_OF_CONTRACT: ["THE_PERSON_DOES_NOT_SHOW_UP_ON_THE_FIRST_DAY"],
};

export const getRetirementTypes = (): string[] => {
  return types;
};

export const getRetirementReasons = (type: string): string[] => {
  return reasons[type] ?? [];
};
